// Medical Knowledge Base — used by the TF-IDF vector search engine
// Each entry has a searchText field (concatenated for indexing) and structured fields for display

export const MEDICAL_KB = [
  // ── CPT CODES ──────────────────────────────────────────────────────────────
  {
    id: 'cpt_99201', type: 'CPT', code: '99201',
    title: 'Office Visit — New Patient, Minimal',
    description: 'Office or outpatient visit for a new patient. Minimal medical decision making.',
    cost_range: '$75–$150', category: 'Office Visit',
    tags: ['office', 'new patient', 'visit', 'outpatient'],
    searchText: 'office visit new patient minimal complexity outpatient evaluation primary care doctor 99201',
  },
  {
    id: 'cpt_99213', type: 'CPT', code: '99213',
    title: 'Office Visit — Established Patient, Low Complexity',
    description: 'Office or outpatient visit for an established patient. Low complexity medical decision making.',
    cost_range: '$100–$200', category: 'Office Visit',
    tags: ['office', 'established patient', 'visit'],
    searchText: 'office visit established patient low complexity outpatient evaluation primary care doctor 99213',
  },
  {
    id: 'cpt_99214', type: 'CPT', code: '99214',
    title: 'Office Visit — Established Patient, Moderate Complexity',
    description: 'Office or outpatient visit for an established patient requiring moderate medical decision making.',
    cost_range: '$150–$300', category: 'Office Visit',
    tags: ['office', 'established patient', 'moderate'],
    searchText: 'office visit established patient moderate complexity outpatient evaluation specialist 99214',
  },
  {
    id: 'cpt_99285', type: 'CPT', code: '99285',
    title: 'Emergency Department Visit — High Complexity',
    description: 'Emergency department visit requiring high complexity medical decision making.',
    cost_range: '$500–$3,000', category: 'Emergency',
    tags: ['emergency', 'ER', 'emergency room', 'urgent'],
    searchText: 'emergency department ER visit high complexity urgent care hospital emergency room 99285',
  },
  {
    id: 'cpt_99283', type: 'CPT', code: '99283',
    title: 'Emergency Department Visit — Moderate Complexity',
    description: 'Emergency department visit with moderate severity presenting problem.',
    cost_range: '$300–$1,200', category: 'Emergency',
    tags: ['emergency', 'ER', 'urgent'],
    searchText: 'emergency department ER visit moderate complexity urgent hospital 99283',
  },
  {
    id: 'cpt_93000', type: 'CPT', code: '93000',
    title: 'Electrocardiogram (EKG/ECG)',
    description: 'Electrocardiogram routine 12-lead with interpretation and report. Checks heart rhythm and electrical activity.',
    cost_range: '$50–$200', category: 'Cardiac',
    tags: ['heart', 'EKG', 'ECG', 'cardiac', 'rhythm'],
    searchText: 'electrocardiogram EKG ECG 12 lead heart rhythm cardiac electrical activity chest pain 93000',
  },
  {
    id: 'cpt_93306', type: 'CPT', code: '93306',
    title: 'Echocardiogram — Complete',
    description: 'Complete transthoracic echocardiogram with spectral Doppler echocardiography. Ultrasound of the heart.',
    cost_range: '$1,000–$3,000', category: 'Cardiac',
    tags: ['heart', 'echo', 'echocardiogram', 'ultrasound', 'cardiac'],
    searchText: 'echocardiogram echo transthoracic doppler heart ultrasound cardiac valve function 93306',
  },
  {
    id: 'cpt_85025', type: 'CPT', code: '85025',
    title: 'Complete Blood Count (CBC)',
    description: 'Complete blood count with differential. Measures red cells, white cells, hemoglobin, hematocrit, and platelets.',
    cost_range: '$30–$100', category: 'Lab',
    tags: ['blood test', 'CBC', 'lab', 'blood count', 'anemia'],
    searchText: 'complete blood count CBC differential white blood cells red blood cells hemoglobin anemia infection lab test 85025',
  },
  {
    id: 'cpt_80053', type: 'CPT', code: '80053',
    title: 'Comprehensive Metabolic Panel (CMP)',
    description: 'Blood test measuring kidney function, liver function, electrolytes, blood sugar, and protein levels.',
    cost_range: '$40–$150', category: 'Lab',
    tags: ['blood test', 'metabolic', 'lab', 'kidney', 'liver', 'glucose'],
    searchText: 'comprehensive metabolic panel CMP kidney liver glucose electrolytes blood chemistry lab test 80053',
  },
  {
    id: 'cpt_80061', type: 'CPT', code: '80061',
    title: 'Lipid Panel (Cholesterol)',
    description: 'Blood test measuring total cholesterol, LDL, HDL, and triglycerides. Used to assess heart disease risk.',
    cost_range: '$30–$100', category: 'Lab',
    tags: ['cholesterol', 'lipid', 'heart', 'LDL', 'HDL', 'triglycerides'],
    searchText: 'lipid panel cholesterol LDL HDL triglycerides cardiovascular risk heart disease blood test 80061',
  },
  {
    id: 'cpt_83036', type: 'CPT', code: '83036',
    title: 'Hemoglobin A1c (HbA1c)',
    description: 'Blood test measuring average blood sugar over 2–3 months. Used to diagnose and monitor diabetes.',
    cost_range: '$30–$90', category: 'Lab',
    tags: ['diabetes', 'A1c', 'blood sugar', 'glucose', 'HbA1c'],
    searchText: 'hemoglobin A1c HbA1c diabetes blood sugar glucose average glycated 83036',
  },
  {
    id: 'cpt_71046', type: 'CPT', code: '71046',
    title: 'Chest X-ray — 2 Views',
    description: 'Chest radiograph, 2 views (frontal and lateral). Used to evaluate lungs, heart, and chest wall.',
    cost_range: '$100–$400', category: 'Radiology',
    tags: ['xray', 'chest', 'radiology', 'lungs', 'x-ray'],
    searchText: 'chest xray x-ray radiograph 2 views lungs heart pneumonia fracture rib radiology 71046',
  },
  {
    id: 'cpt_70553', type: 'CPT', code: '70553',
    title: 'MRI Brain — With Contrast',
    description: 'MRI of the brain with contrast dye (gadolinium). Evaluates tumors, stroke, inflammation, and lesions.',
    cost_range: '$500–$3,500', category: 'Radiology',
    tags: ['MRI', 'brain', 'radiology', 'contrast', 'tumor', 'stroke'],
    searchText: 'MRI brain magnetic resonance imaging contrast gadolinium tumor stroke lesion neurological headache 70553',
  },
  {
    id: 'cpt_70450', type: 'CPT', code: '70450',
    title: 'CT Scan — Head/Brain Without Contrast',
    description: 'Computed tomography of the head without contrast. Fast scan for trauma, bleeding, and stroke.',
    cost_range: '$300–$1,500', category: 'Radiology',
    tags: ['CT', 'CAT scan', 'brain', 'head', 'radiology', 'trauma'],
    searchText: 'CT scan head brain computed tomography without contrast trauma bleeding stroke headache emergency 70450',
  },
  {
    id: 'cpt_74177', type: 'CPT', code: '74177',
    title: 'CT Scan — Abdomen and Pelvis With Contrast',
    description: 'CT of abdomen and pelvis with contrast dye. Evaluates organs including liver, kidneys, intestines.',
    cost_range: '$400–$2,500', category: 'Radiology',
    tags: ['CT', 'abdomen', 'pelvis', 'radiology', 'abdominal pain'],
    searchText: 'CT scan abdomen pelvis computed tomography contrast liver kidney intestine appendix pain 74177',
  },
  {
    id: 'cpt_76700', type: 'CPT', code: '76700',
    title: 'Ultrasound — Abdomen Complete',
    description: 'Complete abdominal ultrasound. Evaluates liver, gallbladder, pancreas, spleen, kidneys, and aorta.',
    cost_range: '$200–$800', category: 'Radiology',
    tags: ['ultrasound', 'abdomen', 'gallbladder', 'liver', 'kidney'],
    searchText: 'ultrasound abdomen complete gallbladder liver kidney pancreas aorta abdominal pain sonogram 76700',
  },
  {
    id: 'cpt_27447', type: 'CPT', code: '27447',
    title: 'Total Knee Replacement',
    description: 'Total knee arthroplasty. Surgical replacement of the knee joint with artificial components.',
    cost_range: '$20,000–$50,000', category: 'Surgery',
    tags: ['knee', 'replacement', 'surgery', 'arthroplasty', 'orthopedic'],
    searchText: 'total knee replacement arthroplasty surgery orthopedic knee joint artificial implant arthritis 27447',
  },
  {
    id: 'cpt_27130', type: 'CPT', code: '27130',
    title: 'Total Hip Replacement',
    description: 'Total hip arthroplasty. Surgical replacement of the hip joint with a prosthetic implant.',
    cost_range: '$20,000–$45,000', category: 'Surgery',
    tags: ['hip', 'replacement', 'surgery', 'arthroplasty', 'orthopedic'],
    searchText: 'total hip replacement arthroplasty surgery orthopedic hip joint artificial implant arthritis 27130',
  },
  {
    id: 'cpt_43239', type: 'CPT', code: '43239',
    title: 'Upper GI Endoscopy With Biopsy',
    description: 'Upper gastrointestinal endoscopy with biopsy. Camera examination of esophagus, stomach, and small intestine.',
    cost_range: '$800–$2,500', category: 'Procedure',
    tags: ['endoscopy', 'GI', 'stomach', 'biopsy', 'gastroscopy'],
    searchText: 'upper GI endoscopy biopsy esophagus stomach duodenum GERD ulcer gastroscopy 43239',
  },
  {
    id: 'cpt_45378', type: 'CPT', code: '45378',
    title: 'Colonoscopy — Diagnostic',
    description: 'Diagnostic colonoscopy. Camera examination of the entire large intestine to detect cancer, polyps, and inflammation.',
    cost_range: '$1,000–$3,500', category: 'Procedure',
    tags: ['colonoscopy', 'colon', 'colorectal', 'cancer screening', 'polyp'],
    searchText: 'colonoscopy colon cancer screening polyp colorectal large intestine diagnostic 45378',
  },
  {
    id: 'cpt_90837', type: 'CPT', code: '90837',
    title: 'Psychotherapy — 60 Minutes',
    description: 'Individual psychotherapy session, 60 minutes. Talk therapy for mental health conditions.',
    cost_range: '$100–$300', category: 'Mental Health',
    tags: ['therapy', 'mental health', 'psychotherapy', 'counseling', 'psychiatry'],
    searchText: 'psychotherapy therapy mental health counseling session 60 minutes depression anxiety psychiatry 90837',
  },
  {
    id: 'cpt_90834', type: 'CPT', code: '90834',
    title: 'Psychotherapy — 45 Minutes',
    description: 'Individual psychotherapy session, 45 minutes. Talk therapy for mental health conditions.',
    cost_range: '$80–$250', category: 'Mental Health',
    tags: ['therapy', 'mental health', 'psychotherapy', 'counseling'],
    searchText: 'psychotherapy therapy mental health counseling session 45 minutes depression anxiety 90834',
  },
  {
    id: 'cpt_99396', type: 'CPT', code: '99396',
    title: 'Preventive Visit — Adult Annual Physical (40–64)',
    description: 'Preventive care visit for patients age 40–64. Annual physical exam including health counseling.',
    cost_range: '$150–$350', category: 'Preventive',
    tags: ['annual physical', 'preventive', 'wellness', 'checkup'],
    searchText: 'preventive care annual physical wellness exam checkup adult health screening 99396',
  },
  {
    id: 'cpt_36415', type: 'CPT', code: '36415',
    title: 'Blood Draw (Venipuncture)',
    description: 'Collection of venous blood by venipuncture. Standard blood draw for lab tests.',
    cost_range: '$5–$30', category: 'Lab',
    tags: ['blood draw', 'venipuncture', 'lab', 'blood test'],
    searchText: 'blood draw venipuncture blood collection lab test phlebotomy 36415',
  },
  {
    id: 'cpt_99213_telehealth', type: 'CPT', code: '99213-95',
    title: 'Telehealth Visit — Established Patient',
    description: 'Telehealth/virtual office visit for established patient. Low to moderate complexity via video or phone.',
    cost_range: '$80–$200', category: 'Telehealth',
    tags: ['telehealth', 'virtual visit', 'video', 'telemedicine', 'remote'],
    searchText: 'telehealth virtual visit telemedicine phone video established patient remote doctor 99213',
  },
  {
    id: 'cpt_d2750', type: 'CPT', code: 'D2750',
    title: 'Dental Crown — Porcelain/Ceramic',
    description: 'Crown restoration — full cast high noble metal or porcelain fused. Covers a damaged tooth.',
    cost_range: '$1,000–$1,800', category: 'Dental',
    tags: ['dental', 'crown', 'tooth', 'porcelain'],
    searchText: 'dental crown tooth porcelain ceramic restoration damaged tooth dentist D2750',
  },
  {
    id: 'cpt_d3310', type: 'CPT', code: 'D3310',
    title: 'Root Canal — Anterior Tooth',
    description: 'Endodontic therapy for an anterior (front) tooth. Removes infected pulp to save the tooth.',
    cost_range: '$700–$1,200', category: 'Dental',
    tags: ['dental', 'root canal', 'tooth', 'endodontic', 'infection'],
    searchText: 'root canal anterior tooth endodontic pulp infection dental pain dentist D3310',
  },
  {
    id: 'cpt_d7210', type: 'CPT', code: 'D7210',
    title: 'Tooth Extraction — Surgical',
    description: 'Surgical extraction of erupted tooth requiring elevation of mucoperiosteal flap and bone removal.',
    cost_range: '$200–$600', category: 'Dental',
    tags: ['dental', 'extraction', 'tooth removal', 'oral surgery'],
    searchText: 'tooth extraction surgical oral surgery wisdom tooth removal dental D7210',
  },

  // ── ICD-10 CODES ───────────────────────────────────────────────────────────
  {
    id: 'icd_I10', type: 'ICD10', code: 'I10',
    title: 'Essential Hypertension',
    description: 'Primary high blood pressure not caused by another condition. A chronic condition managed with medication and lifestyle changes.',
    tags: ['hypertension', 'high blood pressure', 'heart', 'cardiovascular'],
    searchText: 'essential hypertension high blood pressure heart cardiovascular chronic sodium I10',
  },
  {
    id: 'icd_E11', type: 'ICD10', code: 'E11.9',
    title: 'Type 2 Diabetes Mellitus',
    description: 'Type 2 diabetes without complications. A metabolic disease where the body does not use insulin properly.',
    tags: ['diabetes', 'blood sugar', 'insulin', 'metabolic'],
    searchText: 'type 2 diabetes mellitus blood sugar insulin resistance glucose A1c E11',
  },
  {
    id: 'icd_J06', type: 'ICD10', code: 'J06.9',
    title: 'Acute Upper Respiratory Infection',
    description: 'Common cold or upper respiratory infection. Viral infection affecting nose, throat, and sinuses.',
    tags: ['cold', 'respiratory', 'virus', 'sinuses', 'throat'],
    searchText: 'upper respiratory infection cold sinusitis throat nose viral acute J06',
  },
  {
    id: 'icd_M54', type: 'ICD10', code: 'M54.5',
    title: 'Low Back Pain',
    description: 'Lower back pain — the most common musculoskeletal complaint. Can be acute or chronic.',
    tags: ['back pain', 'lower back', 'spine', 'lumbar', 'musculoskeletal'],
    searchText: 'low back pain lumbar spine musculoskeletal chronic acute sciatica M54',
  },
  {
    id: 'icd_F32', type: 'ICD10', code: 'F32.9',
    title: 'Major Depressive Disorder',
    description: 'Clinical depression — persistent low mood, loss of interest, and other symptoms affecting daily life.',
    tags: ['depression', 'mental health', 'mood disorder', 'psychiatry'],
    searchText: 'major depressive disorder depression mental health mood low energy psychiatry F32',
  },
  {
    id: 'icd_F41', type: 'ICD10', code: 'F41.1',
    title: 'Generalized Anxiety Disorder',
    description: 'Persistent, excessive worry about multiple topics. Affects sleep, concentration, and daily functioning.',
    tags: ['anxiety', 'mental health', 'worry', 'GAD'],
    searchText: 'generalized anxiety disorder GAD worry stress mental health psychiatry F41',
  },
  {
    id: 'icd_K21', type: 'ICD10', code: 'K21.0',
    title: 'Gastroesophageal Reflux Disease (GERD)',
    description: 'Chronic acid reflux causing heartburn and potential esophageal damage. Managed with diet and medication.',
    tags: ['GERD', 'acid reflux', 'heartburn', 'stomach', 'esophagus'],
    searchText: 'GERD gastroesophageal reflux acid reflux heartburn stomach esophagus antacid K21',
  },
  {
    id: 'icd_J45', type: 'ICD10', code: 'J45.901',
    title: 'Asthma — Unspecified',
    description: 'Chronic lung condition causing airway inflammation, wheezing, shortness of breath, and coughing.',
    tags: ['asthma', 'breathing', 'lungs', 'inhaler', 'respiratory'],
    searchText: 'asthma wheeze shortness of breath lungs inhaler bronchospasm respiratory J45',
  },
  {
    id: 'icd_N39', type: 'ICD10', code: 'N39.0',
    title: 'Urinary Tract Infection (UTI)',
    description: 'Bacterial infection of the urinary system causing burning urination, frequency, and pelvic pain.',
    tags: ['UTI', 'urinary', 'bladder', 'kidney', 'infection'],
    searchText: 'urinary tract infection UTI bladder burning urination bacteria kidney N39',
  },
  {
    id: 'icd_Z00', type: 'ICD10', code: 'Z00.00',
    title: 'Annual Physical Exam',
    description: 'Encounter for general adult medical examination without abnormal findings. Preventive wellness visit.',
    tags: ['annual physical', 'preventive', 'wellness', 'checkup', 'screening'],
    searchText: 'annual physical exam wellness checkup preventive care general adult medical examination Z00',
  },
  {
    id: 'icd_S82', type: 'ICD10', code: 'S82.002A',
    title: 'Fracture of Patella (Kneecap)',
    description: 'Broken kneecap. Caused by direct trauma or fall. May require surgery or immobilization.',
    tags: ['fracture', 'kneecap', 'bone', 'trauma', 'orthopedic'],
    searchText: 'fracture kneecap patella broken bone knee trauma orthopedic S82',
  },
  {
    id: 'icd_G43', type: 'ICD10', code: 'G43.909',
    title: 'Migraine',
    description: 'Recurrent severe headache often with nausea, vomiting, and light sensitivity. Can be disabling.',
    tags: ['migraine', 'headache', 'neurological', 'nausea'],
    searchText: 'migraine headache severe nausea light sensitivity neurological vomiting G43',
  },
  {
    id: 'icd_E78', type: 'ICD10', code: 'E78.5',
    title: 'Hyperlipidemia (High Cholesterol)',
    description: 'Elevated blood lipids including LDL cholesterol and triglycerides. Increases cardiovascular disease risk.',
    tags: ['cholesterol', 'lipids', 'heart disease', 'LDL', 'statin'],
    searchText: 'hyperlipidemia high cholesterol LDL triglycerides cardiovascular statin lipid E78',
  },
  {
    id: 'icd_J18', type: 'ICD10', code: 'J18.9',
    title: 'Pneumonia',
    description: 'Infection causing inflammation of the air sacs in the lungs. Can be bacterial, viral, or fungal.',
    tags: ['pneumonia', 'lung', 'infection', 'respiratory', 'fever'],
    searchText: 'pneumonia lung infection bacterial viral fever cough respiratory hospitalization J18',
  },
  {
    id: 'icd_K35', type: 'ICD10', code: 'K35.80',
    title: 'Acute Appendicitis',
    description: 'Inflammation of the appendix requiring emergency surgery (appendectomy) to prevent rupture.',
    tags: ['appendicitis', 'appendix', 'surgery', 'emergency', 'abdominal pain'],
    searchText: 'appendicitis appendix acute surgery emergency abdominal pain appendectomy K35',
  },
  {
    id: 'icd_I21', type: 'ICD10', code: 'I21.9',
    title: 'Acute Myocardial Infarction (Heart Attack)',
    description: 'Heart attack — blockage of coronary artery causing heart muscle damage. Medical emergency.',
    tags: ['heart attack', 'myocardial infarction', 'cardiac', 'emergency', 'chest pain'],
    searchText: 'myocardial infarction heart attack cardiac emergency coronary artery chest pain I21',
  },
  {
    id: 'icd_C50', type: 'ICD10', code: 'C50.911',
    title: 'Breast Cancer',
    description: 'Malignant neoplasm of breast. Most common cancer in women. Treated with surgery, chemotherapy, radiation.',
    tags: ['cancer', 'breast', 'tumor', 'oncology', 'chemotherapy'],
    searchText: 'breast cancer malignant tumor oncology chemotherapy radiation surgery mammogram C50',
  },
  {
    id: 'icd_J44', type: 'ICD10', code: 'J44.1',
    title: 'COPD — Acute Exacerbation',
    description: 'Chronic obstructive pulmonary disease flare-up. Worsening of breathing difficulty in a chronic lung disease.',
    tags: ['COPD', 'lungs', 'breathing', 'emphysema', 'bronchitis', 'smoking'],
    searchText: 'COPD chronic obstructive pulmonary disease emphysema bronchitis smoking breathing exacerbation J44',
  },
  {
    id: 'icd_M17', type: 'ICD10', code: 'M17.11',
    title: 'Osteoarthritis of Knee',
    description: 'Degenerative joint disease of the knee. Cartilage breakdown causing pain, stiffness, and reduced mobility.',
    tags: ['arthritis', 'knee', 'osteoarthritis', 'joint pain', 'cartilage'],
    searchText: 'osteoarthritis knee joint pain cartilage degenerative arthritis stiffness M17',
  },
  {
    id: 'icd_Z23', type: 'ICD10', code: 'Z23',
    title: 'Immunization (Vaccine)',
    description: 'Encounter for immunization. Includes flu shots, COVID vaccines, tetanus, and other preventive vaccines.',
    tags: ['vaccine', 'immunization', 'flu shot', 'preventive', 'shot'],
    searchText: 'immunization vaccine flu shot preventive COVID tetanus Z23',
  },

  // ── CONDITIONS ─────────────────────────────────────────────────────────────
  {
    id: 'cond_deductible', type: 'INSURANCE',
    title: 'Deductible',
    description: 'The amount you pay out-of-pocket each year before your insurance starts paying for covered services. Resets January 1st.',
    tags: ['deductible', 'insurance', 'out-of-pocket'],
    searchText: 'deductible amount pay out of pocket before insurance coverage resets annually yearly',
  },
  {
    id: 'cond_copay', type: 'INSURANCE',
    title: 'Copay',
    description: 'A fixed dollar amount you pay for a covered health service, like $25 per office visit or $50 for a specialist. Paid at time of service.',
    tags: ['copay', 'co-pay', 'insurance', 'fixed cost'],
    searchText: 'copay co-pay fixed dollar amount office visit specialist insurance cost',
  },
  {
    id: 'cond_coinsurance', type: 'INSURANCE',
    title: 'Coinsurance',
    description: 'Your percentage share of costs after meeting your deductible. If your coinsurance is 20%, you pay 20% and insurance pays 80%.',
    tags: ['coinsurance', 'insurance', 'percentage', 'cost sharing'],
    searchText: 'coinsurance percentage share cost after deductible insurance pays 80 you pay 20',
  },
  {
    id: 'cond_oop_max', type: 'INSURANCE',
    title: 'Out-of-Pocket Maximum',
    description: 'The most you will pay for covered services in a plan year. After reaching this limit, insurance pays 100% of covered costs.',
    tags: ['out-of-pocket maximum', 'OOP', 'insurance', 'cap', 'limit'],
    searchText: 'out of pocket maximum OOP cap limit insurance pays 100 percent after reaching',
  },
  {
    id: 'cond_prior_auth', type: 'INSURANCE',
    title: 'Prior Authorization',
    description: 'Approval required from your insurance company before receiving certain medications, procedures, or services. Without it, the claim may be denied.',
    tags: ['prior authorization', 'pre-auth', 'approval', 'insurance', 'denial'],
    searchText: 'prior authorization pre-auth approval required insurance before procedure medication denial',
  },
  {
    id: 'cond_network', type: 'INSURANCE',
    title: 'In-Network vs. Out-of-Network',
    description: 'In-network providers have contracts with your insurer and cost less. Out-of-network providers cost significantly more and may not be covered.',
    tags: ['network', 'in-network', 'out-of-network', 'provider', 'insurance'],
    searchText: 'in-network out-of-network provider insurance contract cost less more coverage',
  },
  {
    id: 'cond_eob', type: 'INSURANCE',
    title: 'Explanation of Benefits (EOB)',
    description: 'A statement from your insurance company after a medical visit showing what was billed, what insurance paid, and what you owe. NOT a bill.',
    tags: ['EOB', 'explanation of benefits', 'insurance', 'statement'],
    searchText: 'explanation of benefits EOB insurance statement billed paid owe not a bill',
  },
  {
    id: 'cond_formulary', type: 'INSURANCE',
    title: 'Formulary (Drug List)',
    description: 'A list of prescription drugs covered by your insurance plan. Drugs are organized in tiers — lower tiers cost less.',
    tags: ['formulary', 'drug list', 'prescription', 'insurance', 'medication'],
    searchText: 'formulary drug list prescription covered insurance plan tier medication',
  },
  {
    id: 'cond_appeal', type: 'INSURANCE',
    title: 'Insurance Appeal',
    description: 'A formal request to your insurance company to reconsider a denied claim. Must be filed within 180 days. 40–60% of appeals succeed.',
    tags: ['appeal', 'denied claim', 'insurance', 'reconsideration', 'denial'],
    searchText: 'insurance appeal denied claim reconsideration 180 days formal request letter success',
  },
  {
    id: 'cond_balance_billing', type: 'INSURANCE',
    title: 'Balance Billing (Surprise Bills)',
    description: 'When an out-of-network provider charges the difference between their rate and what insurance paid. The No Surprises Act protects against this in emergencies.',
    tags: ['balance billing', 'surprise bill', 'out-of-network', 'No Surprises Act'],
    searchText: 'balance billing surprise bill out of network provider charge difference No Surprises Act',
  },
  {
    id: 'cond_hmo', type: 'INSURANCE',
    title: 'HMO — Health Maintenance Organization',
    description: 'Insurance plan requiring you to choose a primary care physician (PCP) and get referrals to see specialists. Usually lower premiums but less flexibility.',
    tags: ['HMO', 'insurance plan', 'primary care', 'referral', 'PCP'],
    searchText: 'HMO health maintenance organization primary care physician referral specialist lower cost',
  },
  {
    id: 'cond_ppo', type: 'INSURANCE',
    title: 'PPO — Preferred Provider Organization',
    description: 'Insurance plan with more flexibility to see any doctor or specialist without a referral. Higher premiums but broader network access.',
    tags: ['PPO', 'insurance plan', 'specialist', 'no referral', 'flexibility'],
    searchText: 'PPO preferred provider organization no referral specialist flexibility higher premium broader network',
  },

  // ── PROCEDURES & CONDITIONS ────────────────────────────────────────────────
  {
    id: 'proc_mri', type: 'PROCEDURE',
    title: 'MRI (Magnetic Resonance Imaging)',
    description: 'Imaging test using magnetic fields to create detailed pictures of organs and tissues. No radiation. Used for brain, spine, joints, and soft tissue.',
    cost_range: '$400–$3,500', tags: ['MRI', 'imaging', 'radiology', 'brain', 'spine'],
    searchText: 'MRI magnetic resonance imaging brain spine joint soft tissue no radiation detailed',
  },
  {
    id: 'proc_ct', type: 'PROCEDURE',
    title: 'CT Scan (Computed Tomography)',
    description: 'Fast imaging test using X-rays to create 3D cross-section images. Uses radiation. Common for trauma, chest, abdomen.',
    cost_range: '$300–$6,750', tags: ['CT', 'CAT scan', 'imaging', 'radiology', 'X-ray'],
    searchText: 'CT scan computed tomography CAT scan X-ray 3D cross section fast imaging trauma chest abdomen',
  },
  {
    id: 'proc_colonoscopy', type: 'PROCEDURE',
    title: 'Colonoscopy',
    description: 'Camera examination of the colon. Recommended every 10 years starting at age 45 for colon cancer screening. Covered 100% as preventive care.',
    cost_range: '$1,000–$3,500', tags: ['colonoscopy', 'colon', 'screening', 'cancer prevention'],
    searchText: 'colonoscopy colon cancer screening preventive 45 years old polyp removal examination',
  },
  {
    id: 'proc_mammogram', type: 'PROCEDURE',
    title: 'Mammogram',
    description: 'X-ray screening for breast cancer. Recommended annually for women 40+ or 50+. Usually free as preventive care under ACA.',
    cost_range: '$100–$250 (often free)', tags: ['mammogram', 'breast cancer', 'screening', 'preventive', 'women'],
    searchText: 'mammogram breast cancer screening preventive women 40 50 X-ray ACA free annual',
  },
  {
    id: 'proc_physical_therapy', type: 'PROCEDURE',
    title: 'Physical Therapy',
    description: 'Rehabilitation therapy to restore movement, reduce pain, and improve function after injury or surgery. Requires referral from doctor.',
    cost_range: '$100–$300 per session', tags: ['physical therapy', 'PT', 'rehabilitation', 'injury', 'recovery'],
    searchText: 'physical therapy PT rehabilitation injury surgery recovery pain movement function',
  },
  {
    id: 'proc_chemo', type: 'PROCEDURE',
    title: 'Chemotherapy',
    description: 'Drug treatment that kills cancer cells. Administered intravenously or orally. Often requires multiple cycles.',
    cost_range: '$10,000–$200,000+ per course', tags: ['chemotherapy', 'cancer', 'oncology', 'treatment', 'infusion'],
    searchText: 'chemotherapy cancer treatment oncology infusion IV drug cycle kill tumor cells',
  },
]
